version: 1

sequences:
  - protein:
      id: A
      sequence: CVNNDTLSGDVYTASEAKQVQNVSYGTIVNVRPVQIQGGDQGVQSAMNKTQGVELEIRKDDGNTIMVVQKQGNTRFSPGQRVVLASNGSQVTVSPR
      msa: empty

  - protein:
      id: B
      sequence: CVNNDTLSGDVYTASEAKQVQNVSYGTIVNVRPVQIQGGDQGVQSAMNKTQGVELEIRKDDGNTIMVVQKQGNTRFSPGQRVVLASNGSQVTVSPR
      msa: empty

  - protein:
      id: C
      sequence: SLERQRAALRSIPGATDAQIALVLAATPPSATEEEVIAKGRAFMAAHPEYG
      msa: empty
